pipeline{
  agent any
  stages {
    stage ("build") {
      steps {
        sh 'mvn -f java-tomcat-sample/pom.xml clean package'
      }
      post {
        success{
          archiveArtifacts artifacts:'**/*.war'
        }
      }
    }
    stage ("DockerImage") {
      sh 'docker build -t image1 java-tomcat-sample/.'
    }
  }
}
        
