pipeline{
  agent any
  stages {
    stage ("build") {
      steps {
        sh 'mvn -f java-tomcat-sample/pom.xml clean package'
      }
      post {
        success{
          archiveArtifacts artifacts:'**/*.war'
        }
      }
    }
    stage ("DockerImage") {
      steps { 
        sh 'docker build -t image1 java-tomcat-sample/.'
      }
    }
    stage ("Dockercont") {
      steps {
        sh 'docker run -it --name cont1 -d -p 8081:80 image1'
      }
    }
  }
}
        
